inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('crear/autor', views.crear_autor, name='crear_autor'),
    path('crear/editorial', views.crear_editorial, name='crear_editorial'),
    path('libro/crear', views.crear_libro, name='crear_libro'),
    path('inicio/lista_libros', views.lista_libros, name='lista_libros')
]

mi_web1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

inicio/models.py
from django.db import models

class Autor(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)

class Editorial(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)

class Libro(models.Model):
    titulo = models.CharField(max_length=50)
    autor = models.CharField(max_length=50)
    editorial = models.CharField(max_length=50)

inicio/forms.py
from django import forms
from inicio.models import Autor, Editorial, Libro

class CrearAutorFormulario(forms.Form): 
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)

class CrearEditorialFormulario(forms.Form):
    nombre = forms.CharField(max_length=50)
    direccion = forms.CharField(max_length=100)

class CrearLibroFormulario(forms.Form):
    titulo = forms.CharField(max_length=50)
    autor = forms.CharField(max_length=50)
    editorial = forms.CharField(max_length=50)

class BusquedaFormulario(forms.Form):
    titulo = forms.CharField(max_length=100, required=False)

inicio/views.py
from inicio.forms import CrearAutorFormulario, CrearEditorialFormulario, CrearLibroFormulario, BusquedaFormulario
from inicio.models import Libro, Autor, Editorial
from django.shortcuts import render, redirect

def inicio(request):
    return render(request, 'inicio/inicio.html')

def crear_autor(request):
    if request.method == 'POST':
        formularioA = CrearAutorFormulario(request.POST)
        if formularioA.is_valid():
            info = formularioA.cleaned_data
            autor = Autor(nombre = info ['nombre'], apellido = info ['apellido'])
            autor.save()
        else:
            return render(request, 'inicio/crear_autor.html', {'formularioA': formularioA})
    formularioA = CrearAutorFormulario()
    return render(request, 'inicio/crear_autor.html', {'formularioA': formularioA})

def crear_editorial(request):
    if request.method == 'POST':
        formularioE = CrearEditorialFormulario(request.POST)
        if formularioE.is_valid():
            info = formularioE.cleaned_data
            editorial = Editorial(nombre = info ['nombre'], direccion = info ['direccion'])
            editorial.save()
        else:
            return render(request, 'inicio/crear_editorial.html', {'formularioE': formularioE})
    formularioE = CrearEditorialFormulario()
    return render(request, 'inicio/crear_editorial.html', {'formularioE': formularioE})

def crear_libro(request):
    if request.method == 'POST':
        formularioL = CrearLibroFormulario(request.POST)
        if formularioL.is_valid():
            info = formularioL.cleaned_data
            libro = Libro(titulo = info ['titulo'], autor = info ['autor'], editorial = info ['editorial'])
            libro.save()
            return redirect('inicio:lista_libros')
        else:    
            return render(request, 'inicio/crear_libro.html', {'formularioL': formularioL})
    
    formularioL = CrearLibroFormulario()
    return render(request, 'inicio/crear_libro.html', {'formularioL': formularioL})

def lista_libros(request): 
    formulario = BusquedaFormulario(request.GET)
    if formulario.is_valid():
        busqueda = formulario.cleaned_data['titulo']
        lista_libros = Libro.objects.filter(titulo__icontains=busqueda)
    formulario = BusquedaFormulario()
    return render(request, 'inicio/lista_libros.html', {'formulario':formulario, 'libros':lista_libros})

inicio/templates/inicio/crear_autor.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Autor</title>
{% endblock title_head %}

{% block h1_header %}
Crear Autor
{% endblock h1_header %}

{% block contenido %}
<form action="" method="post">
    {% csrf_token %}
    <Table>
        {{formularioA}}
    </Table>
    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/crear_editorial.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Editorial</title>
{% endblock title_head %}

{% block h1_header %}
Crear Editorial
{% endblock h1_header %}

{% block contenido %}
<form action="" method="post">
    {% csrf_token %}
    <Table>
        {{formularioE}}
    </Table>
    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/crear_libro.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Libro</title>
{% endblock title_head %}

{% block h1_header %}
Crear Libro
{% endblock h1_header %}

{% block contenido %}
<form action="" method="post">
    {% csrf_token %}
    <Table>
        {{formularioL}}
    </Table>
    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
Bienvenidos al Oceano de Libros
{% endblock h1_header %}

{% block contenido %}
<p>
</p>
{% endblock contenido %}

inicio/templates/inicio/lista_libros.html
{% extends 'base.html' %}

{% block title_head %}
<title>Busqueda</title>
{% endblock title_head %}

{% block h1_header %}
Busqueda de Libros
{% endblock h1_header %}

{% block contenido %}

<button>
    <a class="navbar-brad" href={% url 'inicio:crear_libro' %}>Crear libro</a>
</button>

<form action="" method="get">
    {{ formulario }}
    <button type="submit">Buscar</button>
</form>

{% for libro in libros %}
<li>Titulo: {{libro.titulo}} - Autor: {{libro.autor}} - Editorial: {{libro.editorial}}</li>

{% empty %}
<li>No se encontraron libros con ese nombre.</li>
{% endfor %}

{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% block title_head %}
    <title>Landing Page - Start Bootstrap Theme</title>
    {% endblock title_head %}
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"
        type="text/css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href={% static "css/styles.css" %} rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
            <a class="navbar-brand" href={% url 'inicio:crear_autor' %}>Crear Autor</a>
            <a class="navbar-brand" href={% url 'inicio:crear_editorial' %}>Crear Editorial</a>
            <a class="navbar-brand" href={% url 'inicio:lista_libros' %}>Lista de Libros</a>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">
                            {% block h1_header %}
                            {% endblock h1_header %}
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% block contenido %}
    {% endblock contenido %}
    <!-- Footer-->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#!">About</a></li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-facebook fs-3"></i></a>
                        </li>
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-twitter fs-3"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!"><i class="bi-instagram fs-3"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src={% static "js/scripts.js" %}></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>